insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Cheake', 'Corrinne',     3, 'L300', 7, false, 7, 2.0, 36);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Bradburne', 'Ahmed',     4, 'Sportage', 3, true, 6, 2.1, 31);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Godbert', 'Marj',        4, 'Colt', 4, false, 18, 3.5, 52);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Demeza', 'Emery',        5, 'Rio', 2, false, 4, 3.7, 38);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Wallbrook', 'Tymon',     1, 'Jetta', 2, false, 14, 4.0, 50);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Orro', 'Leoine',         4, 'A8', 4, true, 9, 4.0, 41);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('McKeney', 'Casandra',    1, '7 Series', 1, false, 15, 3.1, 46);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Praundlin', 'Benoite',   2, 'Cavalier', 5, false, 19, 2.4, 22);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Ziemen', 'Berty',        2, 'Park Avenue', 4, false, 3, 4.2, 56);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Covington', 'Estevan',   4, 'Exige', 9, false, 13, 3.1, 25);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Kenafaque', 'Colline',   3, 'Bronco', 3, true, 2, 4.4, 48);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Summerrell', 'Nathalia', 2, 'Rondo', 1, false, 12, 3.0, 40);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Silverman', 'Alameda',   5, 'Tahoe', 8, true, 19, 2.7, 52);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Hayward', 'Innis',       2, 'R32', 9, false, 4, 4.2, 25);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Flint', 'Levin',         3, 'M-Class', 4, true, 6, 3.0, 36);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Deinert', 'Delores',     5, 'S40', 1, false, 18, 4.9, 59);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Snelgrove', 'Armstrong', 5, 'rio', 2, true, 16, 1.5, 42);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Biglin', 'Lanna',        5, 'Laser', 5, true, 16, 1.2, 44);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Bontein', 'Jo-ann',      3, 'Rendezvous', 4, false, 2, 1.4, 33);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Bootes', 'Pooh',         1, 'Silverado 1500', 1, true, 9, 3.9, 32);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Doey', 'Clemente',       4, 'Crown Victoria', 1, false, 14, 1.0, 46);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Lamers', 'Isabeau',      5, 'GLC', 2, false, 8, 4.2, 33);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Grahame', 'Ossie',       2, 'Continental Mark VII', 9, true, 10, 3.3, 26);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('MacScherie', 'Odella',   2, '4000', 4, false, 8, 4.1, 22);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Cookney', 'Reeva',       3, 'Club Wagon', 6, false, 10, 4.2, 55);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Tatnell', 'Bram',        1, 'ES', 5, false, 8, 2.6, 24);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Padbery', 'Tamra',       5, 'Dakota', 7, false, 7, 4.0, 30);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Milan', 'Alfredo',       1, 'A8', 2, false, 18, 1.7, 29);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Frudd', 'Analiese',      1, '3500 Club Coupe', 8, false, 10, 3.3, 21);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Hatherleigh', 'Eolande', 4, 'Corolla', 8, true, 11, 3.1, 20);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Domanek', 'Sargent',     2, 'Town Car', 7, false, 7, 1.7, 21);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Bordis', 'Nadeen',       1, 'Express 3500', 1, false, 12, 2.7, 54);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Gallacher', 'Delcine',   5, '330', 5, false, 10, 2.4, 32);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Lomasney', 'Sterling',   5, 'Forester', 2, false, 16, 4.5, 25);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Lopez', 'Nye',           5, 'Ram 2500', 6, true, 3, 1.7, 58);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Josephoff', 'Milo',      5, 'X-90', 5, false, 18, 3.8, 50);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Affleck', 'Shelby',      4, 'SL-Class', 2, false, 1, 3.9, 52);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Nyssens', 'Falkner',     2, 'MR2', 1, false, 15, 1.4, 41);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Stobbes', 'Huntington',  2, 'LaCrosse', 1, false, 15, 1.2, 35);
insert into taxi_driver_info (last_name, first_name, level, car_model, city_id, is_busy, rating, minute_cost) values ('Palek', 'Leela',         1, 'RX-7', 2, false, 2, 4.1, 38);